version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "7860:7860"
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    container_name: backend
    environment:
      - INDEX_DATA=0
      - MODEL_NAME=llama3.2:1B
      - EMBEDDING_MODEL=bge-m3
    depends_on:
      chroma:
        condition: service_healthy
      #ollama
    networks:
      - app-network
    volumes:
      - ./backend:/app 

  chroma:
    image: chromadb/chroma:0.5.13
    volumes:
      - ./chroma:/chroma/.chroma/index
    ports:
      - "8000:8000"
    container_name: chroma
    healthcheck: 
        test: curl localhost:8000/api/v1/heartbeat || exit 1
        interval: 10s
        retries: 2
        start_period: 5s
        timeout: 10s
    networks:
      - app-network

  ollama:
    image: dustynv/ollama:r36.4.0
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    entrypoint: ["/bin/bash", "-c"]
    command: ["( /bin/ollama serve & sleep 5; /bin/ollama run llama3.2:1B )"]
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  app-network:
    driver: bridge
