version: '3'

services:

  chatbot:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "5678:5678"
    container_name: chatbot
    environment:
      - INDEX_DATA=0
      - MODEL_NAME=llama3.2:1B
      - EMBEDDING_MODEL=bge-m3
      - PULL_EMBEDDING_MODEL=0
      - OLLAMA_HOST_NAME=ollama
      - CHROMA_HOST_NAME=chroma
      - PDF_DOC_PATH=/app/src/AI_Book.pdf
    depends_on:
      - chroma
      - ollama
    networks:
      - app-network
    volumes:
      - ./app:/app

  chroma:
    image: chromadb/chroma:0.6.4.dev74
    volumes:
      - ./chroma:/chroma/.chroma/index
    ports:
      - "8000:8000"
    container_name: chroma
    networks:
      - app-network

  ollama:
    image: dustynv/ollama:main-r36.4.0
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    entrypoint: ["/bin/bash", "-c"]
    command: ["( ollama serve & sleep 5; ollama run llama3.2:1B )"]
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  app-network:
    driver: bridge
