[logger]
level = "info"
# this is needed for local development with docker
[server]
# you will need this for local development:
runOnSave = true
# you will need this if running docker on windows host:
fileWatcherType = "poll"