version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "7860:7860"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - chromadb
      - ollama
    volumes:
      - sqlite-data:/app/memory_db  # Mount volume for SQLite memory DB
    networks:
      - app-network

  chromadb:
    image: chromadb/chromadb:latest
    volumes:
      - chromadb-data:/data
    networks:
      - app-network

  ollama:
    image: ghcr.io/jmorganca/ollama:main
    ports:
      - "11434:11434"
    networks:
      - app-network

volumes:
  chromadb-data:
  sqlite-data:

networks:
  app-network:
    driver: bridge
