FROM python:3.10-slim

WORKDIR /app

# Install rye for dependency management
RUN pip install rye

COPY pyproject.toml /app/

# Install dependencies via rye
RUN rye sync

# Install SQLite support for Python
RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev

COPY . /app

EXPOSE 5000
CMD ["python", "app/main.py",]
